In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [9]:
a + b

array([5, 7, 9])

In [8]:
a - b

array([-3, -3, -3])

In [7]:
a * b

array([ 4, 10, 18])

In [ ]:
a / b

In [ ]:
a ** b

In [ ]:
a.dot(b)

In [10]:
a.sum()

np.int64(6)

In [ ]:
a.mean()

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.std()

In [ ]:
a.var()

In [ ]:
a.cumsum()

In [ ]:
a.cumprod()

In [ ]:
a.reshape(3, 1)

In [ ]:
a.reshape(1, 3)

In [ ]:
a.T

In [ ]:
a.T.dot(b)

In [ ]:
a.T.dot(b.T)

In [ ]:
a.T.dot(b.T) == a.dot(b)

In [35]:
arr = np.random.randint(0, 10, size=(3, 3))
print(arr)
print("每列最大值：",np.max(arr, axis=0)) #`axis=0`表示按列求最大值
print("每行最大值：",np.max(arr, axis=1)) #`axis=1`表示按行求最大值

[[2 5 6]
 [5 1 7]
 [6 3 5]]
每列最大值： [6 5 7]
每行最大值： [6 7 6]


In [42]:
np.random.seed(0)
arr = np.random.randint(0, 10, size=(3, 3))
print(arr)
arr[0:2, 0:2] = 0
print(arr)

[[5 0 3]
 [3 7 9]
 [3 5 2]]
[[0 0 3]
 [0 0 9]
 [3 5 2]]
